name: Publish

on:
  push:
    branches:
      - master

jobs:
  charm:
    name: Charm
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install charm --classic
        sudo pip3 install charmcraft

    - name: Publish bundle
      env:
        CHARMSTORE_CREDENTIAL: ${{ secrets.CHARMSTORE_CREDENTIAL }}
      run: |
        set -eux
        echo $CHARMSTORE_CREDENTIAL > ~/.go-cookies
        IMAGE_TAG="1.6.0"
        charmcraft build
        docker pull docker.io/seldonio/seldon-core-operator:1.6.0:$IMAGE_TAG
        charm push ./seldon-controller-manager.charm \
            cs:~seldon-charmers/seldon-controller-manager \
            --resource oci-image=docker.io/seldonio/seldon-core-operator:1.6.0:$IMAGE_TAG


